name: Backend Continuous Integration

defaults:
  run:
    working-directory: app/backend

on:
  pull_request:
    branches:
      - main
    paths:
      - app/backend/**
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install all dependencies
        run: pipenv install -d

      - name: Run linting
        run: pipenv run lint
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install all dependencies
        run: pipenv install -d

      - name: Run testing
        run: pipenv run test
        continue-on-error: false

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [lint, test]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build the application using Docker
        run: docker build .
        continue-on-error: false
