name: Frontend Continuous Integration

defaults:
  run:
    working-directory: app/frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - app/frontend/**
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linting
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: app/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    name: Run testing
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: app/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: false

  build:
    runs-on: ubuntu-latest
    name: Build the application
    needs: [lint, test]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build the application using Docker
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://placeholder-url .
        continue-on-error: false
